### ISSUE TITLE
Add Statistics Page

### ISSUE THREAD

**Issue by prawnydagrate** [safwansamsudeen/infilib#34]
For the Members section, I'm thinking of a pie chart, and we have some options

1. One pie chart that shows the distribution of users by gender, and another pie chart that shows the distribution of users by activity, and another that shows distribution by century
2. You get the point

I'm not sure which would be ideal, so tell me @safwansamsudeen, and I'll try to use a chart library to display the data

**Comment by safwansamsudeen** [comment]
### Members
> One pie chart that shows the distribution of users by gender, and another pie chart that shows the distribution of users by activity, and another that shows distribution by century

Yep - gender and age group (0-10, 10-20...). We'd also like to see break ups of **subscription types**.

It's unclear what you mean by activity - but perhaps it might be redundant, as #27 will address something like this.

### Items
- Track the overall items over time (we'll have to add the `created_at` field to the DB before this)
-  **Item types:** Compare the distribution of books vs. magazines.
- **Item status:** Track the proportion of available, borrowed, reference, or lost items (here, we need to access both the `status` (which can be `IN`, `OUT`, `UNAVAILABLE`) and the `reference` boolean field).
- **Language, authors, categories, and publishers:** pie charts for each.

### Borrows
-  **Trends:** Chart borrowing activity over time (daily, weekly, monthly).

All of these need to be time-duration bound (all time, last year, last month, so on)
- **Average borrow duration:** Track how long items typically remain checked out.
-  **Authors, publisher, categories, languages:** pie charts for each _in the borrowed books_

We'll update this as we get more ideas.

**Comment by safwansamsudeen** [comment]
This is being worked on in #39.

**Comment by safwansamsudeen** [comment]
We've completed a basic version, but need more improvements.

**Comment by safwansamsudeen** [comment]
I think we can close this for now - it's decent.
